export enum AuthActionKind {
  SET_USER = "SET_USER",
  SET_LOADING = "SET_LOADING",
};

export enum BookActionKind {
  SET_BOOKS = "SET_BOOKS",
  SET_STATUS = "SET_STATUS",
  TOGGLE_MODE = "TOGGLE_MODE",
  UPDATE_LIKES = "UPDATE_LIKES",
  SET_USER_CONCEPTS = "SET_USER_CONCEPTS",
};

export enum TournamentActionKind {
  SET_TOURNAMENTS = "SET_TOURNAMENTS",
  SET_TOURNAMENT = "SET_TOURNAMENT",
  SET_STATUS = "SET_STATUS",
};